In [1]:
import pandas as pd
import pyodbc
import matplotlib.pyplot as plt

In [2]:
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOP-JT7GQBL\SQLEXPRESS;'
                      'Database=AdventureWorks;'
                      'Trusted_Connection=yes;')

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute('SELECT COLUMN_NAME, * FROM INFORMATION_SCHEMA.COLUMNS')
rows = cursor.fetchall()
rows

[('BusinessEntityID', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'BusinessEntityID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('FirstName', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'FirstName', 2, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('MiddleName', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'MiddleName', 3, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('LastName', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'LastName', 4, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('TelephoneNumber', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'TelephoneNumber', 5, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('TelephoneSpecialInstructions', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'TelephoneSpecialInstructions', 6, None, 'YES', 'nvarchar', -1, -1, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('Street', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'Street', 7, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('City', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'City', 8, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('StateProvince', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'StateProvince', 9, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('PostalCode', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'PostalCode', 10, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('CountryRegion', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'CountryRegion', 11, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('HomeAddressSpecialInstructions', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'HomeAddressSpecialInstructions', 12, None, 'YES', 'nvarchar', -1, -1, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('EMailAddress', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'EMailAddress', 13, None, 'YES', 'nvarchar', 128, 256, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('EMailSpecialInstructions', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'EMailSpecialInstructions', 14, None, 'YES', 'nvarchar', -1, -1, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('EMailTelephoneNumber', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'EMailTelephoneNumber', 15, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('rowguid', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'rowguid', 16, None, 'NO', 'uniqueidentifier', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
 ('ModifiedDate', 'AdventureWorks', 'Person', 'vAdditionalContactInfo', 'ModifiedDate', 17, None, 'NO', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('BusinessEntityID', 'AdventureWorks', 'Person', 'PersonPhone', 'BusinessEntityID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('PhoneNumber', 'AdventureWorks', 'Person', 'PersonPhone', 'PhoneNumber', 2, None, 'NO', 'nvarchar', 25, 50, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Phone'),
 ('PhoneNumberTypeID', 'AdventureWorks', 'Person', 'PersonPhone', 'PhoneNumberTypeID', 3, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('ModifiedDate', 'AdventureWorks', 'Person', 'PersonPhone', 'ModifiedDate', 4, '(getdate())', 'NO', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('BusinessEntityID', 'AdventureWorks', 'HumanResources', 'vEmployee', 'BusinessEntityID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Title', 'AdventureWorks', 'HumanResources', 'vEmployee', 'Title', 2, None, 'YES', 'nvarchar', 8, 16, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('FirstName', 'AdventureWorks', 'HumanResources', 'vEmployee', 'FirstName', 3, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('MiddleName', 'AdventureWorks', 'HumanResources', 'vEmployee', 'MiddleName', 4, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('LastName', 'AdventureWorks', 'HumanResources', 'vEmployee', 'LastName', 5, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('Suffix', 'AdventureWorks', 'HumanResources', 'vEmployee', 'Suffix', 6, None, 'YES', 'nvarchar', 10, 20, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('JobTitle', 'AdventureWorks', 'HumanResources', 'vEmployee', 'JobTitle', 7, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('PhoneNumber', 'AdventureWorks', 'HumanResources', 'vEmployee', 'PhoneNumber', 8, None, 'YES', 'nvarchar', 25, 50, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Phone'),
 ('PhoneNumberType', 'AdventureWorks', 'HumanResources', 'vEmployee', 'PhoneNumberType', 9, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('EmailAddress', 'AdventureWorks', 'HumanResources', 'vEmployee', 'EmailAddress', 10, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('EmailPromotion', 'AdventureWorks', 'HumanResources', 'vEmployee', 'EmailPromotion', 11, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('AddressLine1', 'AdventureWorks', 'HumanResources', 'vEmployee', 'AddressLine1', 12, None, 'NO', 'nvarchar', 60, 120, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('AddressLine2', 'AdventureWorks', 'HumanResources', 'vEmployee', 'AddressLine2', 13, None, 'YES', 'nvarchar', 60, 120, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('City', 'AdventureWorks', 'HumanResources', 'vEmployee', 'City', 14, None, 'NO', 'nvarchar', 30, 60, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('StateProvinceName', 'AdventureWorks', 'HumanResources', 'vEmployee', 'StateProvinceName', 15, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('PostalCode', 'AdventureWorks', 'HumanResources', 'vEmployee', 'PostalCode', 16, None, 'NO', 'nvarchar', 15, 30, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('CountryRegionName', 'AdventureWorks', 'HumanResources', 'vEmployee', 'CountryRegionName', 17, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('AdditionalContactInfo', 'AdventureWorks', 'HumanResources', 'vEmployee', 'AdditionalContactInfo', 18, None, 'YES', 'xml', -1, -1, None, None, None, None, None, None, None, None, None, None, None, None, None),
 ('TerritoryID', 'AdventureWorks', 'Sales', 'SalesTerritory', 'TerritoryID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Name', 'AdventureWorks', 'Sales', 'SalesTerritory', 'Name', 2, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('CountryRegionCode', 'AdventureWorks', 'Sales', 'SalesTerritory', 'CountryRegionCode', 3, None, 'NO', 'nvarchar', 3, 6, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('Group', 'AdventureWorks', 'Sales', 'SalesTerritory', 'Group', 4, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('SalesYTD', 'AdventureWorks', 'Sales', 'SalesTerritory', 'SalesYTD', 5, '((0.00))', 'NO', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('SalesLastYear', 'AdventureWorks', 'Sales', 'SalesTerritory', 'SalesLastYear', 6, '((0.00))', 'NO', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('CostYTD', 'AdventureWorks', 'Sales', 'SalesTerritory', 'CostYTD', 7, '((0.00))', 'NO', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('CostLastYear', 'AdventureWorks', 'Sales', 'SalesTerritory', 'CostLastYear', 8, '((0.00))', 'NO', 'money', None, None, 19, 10, 4, None, None, None, None, None, None, None, None, None, None),
 ('rowguid', 'AdventureWorks', 'Sales', 'SalesTerritory', 'rowguid', 9, '(newid())', 'NO', 'uniqueidentifier', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
 ('ModifiedDate', 'AdventureWorks', 'Sales', 'SalesTerritory', 'ModifiedDate', 10, '(getdate())', 'NO', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('BusinessEntityID', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'BusinessEntityID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Title', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'Title', 2, None, 'YES', 'nvarchar', 8, 16, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('FirstName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'FirstName', 3, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('MiddleName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'MiddleName', 4, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('LastName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'LastName', 5, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('Suffix', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'Suffix', 6, None, 'YES', 'nvarchar', 10, 20, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('JobTitle', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'JobTitle', 7, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('Department', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'Department', 8, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('GroupName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'GroupName', 9, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('StartDate', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartment', 'StartDate', 10, None, 'NO', 'date', None, None, None, None, None, 0, None, None, None, None, None, None, None, None, None),
 ('PhoneNumberTypeID', 'AdventureWorks', 'Person', 'PhoneNumberType', 'PhoneNumberTypeID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Name', 'AdventureWorks', 'Person', 'PhoneNumberType', 'Name', 2, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('ModifiedDate', 'AdventureWorks', 'Person', 'PhoneNumberType', 'ModifiedDate', 3, '(getdate())', 'NO', 'datetime', None, None, None, None, None, 3, None, None, None, None, None, None, None, None, None),
 ('BusinessEntityID', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'BusinessEntityID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Title', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'Title', 2, None, 'YES', 'nvarchar', 8, 16, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('FirstName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'FirstName', 3, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('MiddleName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'MiddleName', 4, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('LastName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'LastName', 5, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('Suffix', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'Suffix', 6, None, 'YES', 'nvarchar', 10, 20, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('Shift', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'Shift', 7, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('Department', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'Department', 8, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('GroupName', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'GroupName', 9, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('StartDate', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'StartDate', 10, None, 'NO', 'date', None, None, None, None, None, 0, None, None, None, None, None, None, None, None, None),
 ('EndDate', 'AdventureWorks', 'HumanResources', 'vEmployeeDepartmentHistory', 'EndDate', 11, None, 'YES', 'date', None, None, None, None, None, 0, None, None, None, None, None, None, None, None, None),
 ('BusinessEntityID', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'BusinessEntityID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Title', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'Title', 2, None, 'YES', 'nvarchar', 8, 16, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('FirstName', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'FirstName', 3, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('MiddleName', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'MiddleName', 4, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('LastName', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'LastName', 5, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('Suffix', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'Suffix', 6, None, 'YES', 'nvarchar', 10, 20, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('PhoneNumber', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'PhoneNumber', 7, None, 'YES', 'nvarchar', 25, 50, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Phone'),
 ('PhoneNumberType', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'PhoneNumberType', 8, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('EmailAddress', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'EmailAddress', 9, None, 'YES', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('EmailPromotion', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'EmailPromotion', 10, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('AddressType', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'AddressType', 11, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('AddressLine1', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'AddressLine1', 12, None, 'NO', 'nvarchar', 60, 120, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('AddressLine2', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'AddressLine2', 13, None, 'YES', 'nvarchar', 60, 120, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('City', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'City', 14, None, 'NO', 'nvarchar', 30, 60, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('StateProvinceName', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'StateProvinceName', 15, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('PostalCode', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'PostalCode', 16, None, 'NO', 'nvarchar', 15, 30, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', None, None, None),
 ('CountryRegionName', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'CountryRegionName', 17, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),
 ('Demographics', 'AdventureWorks', 'Sales', 'vIndividualCustomer', 'Demographics', 18, None, 'YES', 'xml', -1, -1, None, None, None, None, None, None, None, None, None, None, None, None, None),
 ('ProductID', 'AdventureWorks', 'Production', 'Product', 'ProductID', 1, None, 'NO', 'int', None, None, 10, 10, 0, None, None, None, None, None, None, None, None, None, None),
 ('Name', 'AdventureWorks', 'Production', 'Product', 'Name', 2, None, 'NO', 'nvarchar', 50, 100, None, None, None, None, None, None, 'UNICODE', None, None, 'French_CI_AS', 'AdventureWorks', 'dbo', 'Name'),

In [5]:
Headerlist=[]
for i in range(len(rows)):
    if rows[i][3]=='SalesOrderHeader':
        Headerlist.append(rows[i][0])
print (Headerlist)

['SalesOrderID', 'RevisionNumber', 'OrderDate', 'DueDate', 'ShipDate', 'Status', 'OnlineOrderFlag', 'SalesOrderNumber', 'PurchaseOrderNumber', 'AccountNumber', 'CustomerID', 'SalesPersonID', 'TerritoryID', 'BillToAddressID', 'ShipToAddressID', 'ShipMethodID', 'CreditCardID', 'CreditCardApprovalCode', 'CurrencyRateID', 'SubTotal', 'TaxAmt', 'Freight', 'TotalDue', 'Comment', 'rowguid', 'ModifiedDate']

In [6]:
df = pd.read_csv('C:\\Users\\yoyo\\Documents\\Adventure Works\\AdventureWorks\AdventureWorks-csv (copy samples)\\SalesOrderHeader.csv', '\t',
                names=Headerlist)
df.shape
df.head()
# print(type(df))

,SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,OnlineOrderFlag,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,...,CreditCardID,CreditCardApprovalCode,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment,rowguid,ModifiedDate
0,43659,8,2011-05-31 00:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,5,0,SO43659,PO522145787,10-4020-000676,...,16281.0,105041Vi84182,NaN,20565.6206,1971.5149,616.0984,23153.2339,NaN,{79B65321-39CA-4115-9CBA-8FE0903E12E6},2011-06-07 00:00:00
1,43660,8,2011-05-31 00:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,5,0,SO43660,PO18850127500,10-4020-000117,...,5618.0,115213Vi29411,NaN,1294.2529,124.2483,38.8276,1457.3288,NaN,{738DC42D-D03B-48A1-9822-F95A67EA7389},2011-06-07 00:00:00
2,43661,8,2011-05-31 00:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,5,0,SO43661,PO18473189620,10-4020-000442,...,1346.0,85274Vi6854,4.0,32726.4786,3153.7696,985.5530,36865.8012,NaN,{D91B9131-18A4-4A11-BC3A-90B6F53E9D74},2011-06-07 00:00:00
3,43662,8,2011-05-31 00:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,5,0,SO43662,PO18444174044,10-4020-000227,...,10456.0,125295Vi53935,4.0,28832.5289,2775.1646,867.2389,32474.9324,NaN,{4A1ECFC0-CC3A-4740-B028-1C50BB48711C},2011-06-07 00:00:00
4,43663,8,2011-05-31 00:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,5,0,SO43663,PO18009186470,10-4020-000510,...,4322.0,45303Vi22691,NaN,419.4589,40.2681,12.5838,472.3108,NaN,{9B1E7A40-6AE0-4AD3-811C-A64951857C4B},2011-06-07 00:00:00

In [39]:
df_Table_SalesOrderHeader=df[["SalesOrderID","OrderDate","DueDate","ShipDate","OnlineOrderFlag","CustomerID","SalesPersonID","BillToAddressID","ShipToAddressID","TotalDue","ModifiedDate"]]
df_Table_SalesOrderHeader.to_csv('C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\AW\\SalesOrderHeader1.csv',index=False)

In [16]:
cursor = conn.cursor()

In [42]:
cursor.execute('select top 10 * from sales.Customer join person.person on person.person.BusinessEntityID=sales.Customer.PersonID;')
rows = cursor.fetchall()
len(rows[1])

20